//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Input_ActionSet_ViveBase p_ViveBase;
        
        public static SteamVR_Input_ActionSet_ViveBase ViveBase
        {
            get
            {
                return SteamVR_Actions.p_ViveBase.GetCopy<SteamVR_Input_ActionSet_ViveBase>();
            }
        }
        
        private static void StartPreInitActionSets()
        {
            SteamVR_Actions.p_ViveBase = ((SteamVR_Input_ActionSet_ViveBase)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_ViveBase>("/actions/ViveBase")));
            Valve.VR.SteamVR_Input.actionSets = new Valve.VR.SteamVR_ActionSet[] {
                    SteamVR_Actions.ViveBase};
        }
    }
}
